apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: go-demo-pipeline-run-1
spec:
  serviceAccountName: tekton-cicd
  pipelineRef:
    name: go-demo-pipeline
  resources:
    - name: git-source
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/fc277073030/go-demo.git
    - name: image-source
      resourceSpec:
        type: image
        params:
          - name: url
            value: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/go-demo:latest
