apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-demo-image
spec:
  type: image
  params:
    - name: url
      value: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/go-demo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-demo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/fc277073030/tekton-cicd.git
---
# Builds an image via kaniko and pushes it to registry.
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push-kaniko
spec:
  inputs:
    resources:
      - name: git-resp
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/git-resp/app/Dockerfile
      - name: pathToContext
        description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/git-resp/app
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
        - --cache=true
        - --cache-dir=/cache
      volumeMounts:
        - name: kaniko-cache
          mountPath: /cache
  volumes:
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache-claim

#        - --oci-layout-path=$(inputs.resources.builtImage.path)
#      securityContext:
#        runAsUser: 0
#  sidecars:
#    - image: registry
#      name: registry
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-push-kaniko
spec:
  serviceAccountName: tekton-cicd
  taskRef:
    name: build-push-kaniko
  inputs:
    resources:
      - name: git-resp
        resourceRef:
          name: go-demo-git
    params:
      - name: pathToDockerFile
        value: /workspace/git-resp/app/Dockerfile
      - name: pathToContext
        value: /workspace/git-resp/app
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: go-demo-image