apiVersion: v1
kind: Pod
metadata:
  name: kaniko-warmer
spec:
  containers:
    - name: kaniko-warmer
      image: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/warmer:latest
      args: ["--cache-dir=/cache",
             "--image=ubuntu",
             "--image=openjdk:8-jdk-slim",
             "--image=golang:latest",
             "--image=golang:alpine3.10",
             "--image=python:3.7"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
        - name: kaniko-cache
          mountPath: /cache
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: aliyun-docker-registry
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache-claim
