apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: say-hello
spec:
  inputs:
    params:
      - name: gitrevision
        description: git commit id
        type: string
    resources:
      - name: git-source
        type: git
  steps:
    - name: say-hi
      image: bash
      command: ["bash", "-c"]
      args:
        - echo -e 'Hello is $(inputs.params.gitrevision)'
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: gitrevision
      description: git commit id
      type: string
  resources:
    - name: git-source
      type: git
  tasks:
    - name: say-hello
      taskRef:
        name: say-hello
      params:
        - name: gitrevision
          value: $(params.gitrevision)
      resources:
        inputs:
          - name: git-source
            resource: git-source

