apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
#    - name: message
#      description: The message to print
#      default: This is the default message
#    - name: contenttype
#      description: The Content-Type of the event
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: go-demo-pipeline-run-
      spec:
        serviceAccountName: tekton-cicd
        pipelineRef:
          name: go-demo-pipeline
        resources:
          - name: git-repo
            resourceRef:
              name: go-demo-git
          - name: image-registry
            resourceRef:
              name: go-demo-image