apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: go-demo-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: image-source
      type: image
  tasks:
    - name: build-push-kaniko
      taskRef:
        name: build-push-kaniko
      params:
        - name: pathToDockerFile
          value: /workspace/git-source/app/Dockerfile
        - name: pathToContext
          value: /workspace/git-source/app
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: builtImage
            resource: image-source