apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: go-demo-pipeline
spec:
  resources:
    - name: git-repo
      type: git
    - name: image-registry
      type: image
  tasks:
    - name: build-push-kaniko
      taskRef:
        name: build-push-kaniko
      params:
        - name: pathToDockerFile
          value: /workspace/git-repo/app/Dockerfile
        - name: pathToContext
          value: /workspace/git-repo/app #configure: may change according to your source
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
        outputs:
          - name: builtImage
            resource: image-registry
